### ISSUE TITLE
Browser console error in root selection

### ISSUE THREAD

**Issue by peetereczek** [skaut/skaut-google-drive-gallery#1973]
I have configured plugin and it's listing directories in the settings, but does not list any photos from configured root

<img width="368" alt="image" src="https://github.com/skaut/skaut-google-drive-gallery/assets/42431204/a4e24f02-a12e-4c57-bb0a-f9ec2700eb76">

Google Drive
<img width="423" alt="image" src="https://github.com/skaut/skaut-google-drive-gallery/assets/42431204/a2df97da-74b1-43f1-9925-438d98269267">

In console after opening page where gallery should be displayed (https://jarmoszko.pl/slub/galeria-zdjec/) I can see an error:
Uncaught ReferenceError: sgdgShortcodeLocalize is not defined
    at t.get (shortcode.min.js?ver=1683757439:2:3581)
    at new t (shortcode.min.js?ver=1683757439:2:1527)
    at HTMLDivElement.<anonymous> (shortcode.min.js?ver=1683757439:2:9671)
    at Function.each (jquery.min.js?ver=3.6.3:2:3003)
    at e.<computed>.each (jquery.min.js?ver=3.6.3:2:1481)
    at Object.init (shortcode.min.js?ver=1683757439:2:9579)
    at shortcode.min.js?ver=1683757439:2:10118
    at HTMLDocument.<anonymous> (shortcode.min.js?ver=1683757439:2:10125)
    at e (jquery.min.js?ver=3.6.3:2:30158)
    at t (jquery.min.js?ver=3.6.3:2:30460)

Any advice how I can fix it?

**Comment by marekdedic** [comment]
Hi,
this is intended behaviour - the plugin doesn't show images in the administration interface. If you save the gallery, they should be shown on the actual website.

I'll keep this open due to the console error - that shouldn't be there.

Also, we are aware that this UX isn't the greatest and would want to fix it *some day*...

**Comment by lukasprelovsky** [comment]
Dobry den, 

mam ten isty problem.

V konzole:

jQuery.Deferred exception: sgdgShortcodeLocalize is not defined t.prototype.get@https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2:3557
t@https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2:1527
init/<@https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2:9671
each@https://www.test.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:3003
each@https://www.test.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:1481
init@https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2:9579
@https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2:10118
@https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2:10125
e@https://www.test.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:30038
Deferred/then/l/</t<@https://www.test.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:30340
 undefined

Uncaught ReferenceError: sgdgShortcodeLocalize is not defined
    get https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    t https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    init https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    jQuery 2
    init https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    <anonymous> https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    <anonymous> https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    jQuery 2
[shortcode.min.js:2:3557](https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962)
    get https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    t https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    init https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    jQuery 2
    init https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    <anonymná> https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    <anonymná> https://www.test.sk/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1686646962:2
    jQuery 2
        e
        t


vidim to iste co ten prvy pan, viem si rozkliknut zlozku, definovat si root, ale galeria loaduje a nenacita:

![gale](https://github.com/skaut/skaut-google-drive-gallery/assets/15073394/668f5b21-9c99-473c-9a4a-590e28b26272)

nejake riesenie? 

Vdaka

**Comment by marekdedic** [comment]
Dobrý den,
tato chyba je nejčastěji způsobena pluginy na optimalizaci/minifikaci - pokud nějaký máte zapnutý, zkuste ho vypnout, abychom viděli, zda to je tím.

**Comment by KubisonFromKDE** [comment]
Zdravím, 
bohužel se musím taky přidat k diskuzi a oznámit, že mám stejný/podobný problém a chtěl bych se tady zeptat na radu. Složku si můžu vybrat, ale galerie se nezobrazí a prostě se to jen pořád načítá. Prohledal jsem snad všechny problémy na tomto vašem githubu, ale jediný tento se tomu podobá, ale není to asi úplně ono. Snad jsem tady vše popsal a dodal potřebné informace, kdyžtak se omlouvám a případně napište do odpovědi, co mi chybí a já to dodám.

**Info:**
- **PHP verze:** 8.2.13
- **WP verze:** 6.4.3
- **`<Cenzura>`/Cenzura:** URL adresa/název stránky/tokeny (tokeny jsou samozřejmě). Doufám, že daná cenzura nevadí.

**Konzole:**
- Varování:
`jQuery.Deferred exception: sgdgShortcodeLocalize is not defined ReferenceError: sgdgShortcodeLocalize is not defined
    at t.get (https://www.<Cenzura>.cz/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1706651043:2:3775)
    at new t (https://www.<Cenzura>.cz/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1706651043:2:1721)
    at HTMLDivElement.<anonymous> (https://www.<Cenzura>.cz/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1706651043:2:9948)
    at Function.each (https://c0.wp.com/c/6.4.3/wp-includes/js/jquery/jquery.min.js:2:3129)
    at e.<computed>.each (https://c0.wp.com/c/6.4.3/wp-includes/js/jquery/jquery.min.js:2:1594)
    at Object.init (https://www.<Cenzura>.cz/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1706651043:2:9856)
    at https://www.<Cenzura>.cz/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1706651043:2:10395
    at HTMLDocument.<anonymous> (https://www.<Cenzura>.cz/wp-content/plugins/skaut-google-drive-gallery/frontend/js/shortcode.min.js?ver=1706651043:2:10403)
    at e (https://c0.wp.com/c/6.4.3/wp-includes/js/jquery/jquery.min.js:2:27028)
    at t (https://c0.wp.com/c/6.4.3/wp-includes/js/jquery/jquery.min.js:2:27330) undefined`

- Chyba:
`Uncaught ReferenceError: sgdgShortcodeLocalize is not defined
    at t.get (shortcode.min.js?ver=1706651043:2:3775)
    at new t (shortcode.min.js?ver=1706651043:2:1721)
    at HTMLDivElement.<anonymous> (shortcode.min.js?ver=1706651043:2:9948)
    at Function.each (jquery.min.js:2:3129)
    at e.<computed>.each (jquery.min.js:2:1594)
    at Object.init (shortcode.min.js?ver=1706651043:2:9856)
    at shortcode.min.js?ver=1706651043:2:10395
    at HTMLDocument.<anonymous> (shortcode.min.js?ver=1706651043:2:10403)
    at e (jquery.min.js:2:27028)
    at t (jquery.min.js:2:27330)
pixel.wp`

**Přikládám obrázek, co to vlastně dělá (neboli pořád to načítá):**
![image](https://github.com/skaut/skaut-google-drive-gallery/assets/67206839/311494ba-cc93-48bf-9724-a84b08e96894)

**Základní nastavení:**
![image](https://github.com/skaut/skaut-google-drive-gallery/assets/67206839/a807fe77-b414-4788-9e6f-a805571f900f)


**Pokročilé nastavení:**
Do toho jsem nešahal zatím, protože nebylo potřeba.

S pozdravem Kubison
