### ISSUE TITLE
Failed to parse batch request

### ISSUE THREAD

**Issue by Honny1** [skaut/skaut-google-drive-gallery#2155]
After granting permission, I get this error message:
```
The Image and video gallery from Google Drive plugin has encountered an error. Error message:

[{ "error": { "code": 400, "message": "Failed to parse batch request, error: 0 items. Received batch body: (0) bytes redacted", "errors": [ { "message": "Failed to parse batch request, error: 0 items. Received batch body: (0) bytes redacted", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } } ]

Stack trace:

#0 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Http/REST.php(82): Sgdg\Vendor\Google\Http\REST::decodeHttpResponse()
#1 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Task/Runner.php(153): Sgdg\Vendor\Google\Http\REST::doExecute()
#2 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Http/REST.php(53): Sgdg\Vendor\Google\Task\Runner->run()
#3 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Client.php(739): Sgdg\Vendor\Google\Http\REST::execute()
#4 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Http/Batch.php(92): Sgdg\Vendor\Google\Client->execute()
#5 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(292): Sgdg\Vendor\Google\Http\Batch->execute()
#6 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Task/Runner.php(153): Sgdg\API_Client::Sgdg\{closure}()
#7 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(307): Sgdg\Vendor\Google\Task\Runner->run()
#8 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(116): Sgdg\API_Client::execute()
#9 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/helpers/class-helpers.php(42): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::ajax_handler_body()
#10 /home/users/hony8ucz/hony.8u.cz/web/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(53): Sgdg\Helpers::ajax_wrapper()
#11 /home/users/hony8ucz/hony.8u.cz/web/wp-includes/class-wp-hook.php(310): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::handle_ajax()
#12 /home/users/hony8ucz/hony.8u.cz/web/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#13 /home/users/hony8ucz/hony.8u.cz/web/wp-includes/plugin.php(517): WP_Hook->do_action()
#14 /home/users/hony8ucz/hony.8u.cz/web/wp-admin/admin-ajax.php(188): do_action()
#15 {main}
```
php: 7.3
wordpress: 6.3
plugin: 2.13.5

**Comment by Honny1** [comment]
Is it possible that this error is caused by using `http` instead of `https`?

**Comment by marekdedic** [comment]
Thanks for the report, HTTPS has nothing to do with this, however, I am surprised Google even allows you to connect the website over plain HTTP if you're doing that...
