### ISSUE TITLE
refresh token must be passed in or set as part of setAccessToken

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#2172]
V pluginu Galerie obrázků a videí z Google Disku nastala chyba. Chybová hláška:
refresh token must be passed in or set as part of setAccessToken
Stack trace:
#0 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(116): Sgdg\Vendor\Google\Client->fetchAccessTokenWithRefreshToken()
#1 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(134): Sgdg\API_Client::get_authorized_raw_client()
#2 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(152): Sgdg\API_Client::get_drive_client()
#3 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/class-api-facade.php(87): Sgdg\API_Client::initialize_batch()
#4 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(132): Sgdg\API_Facade::get_drive_name()
#5 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(75): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::path_ids_to_names()
#6 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/helpers/class-helpers.php(42): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::ajax_handler_body()
#7 /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(53): Sgdg\Helpers::ajax_wrapper()
#8 /DISK3/www/4172/petkapraha.cz/www/wp-includes/class-wp-hook.php(310): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::handle_ajax()
#9 /DISK3/www/4172/petkapraha.cz/www/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#10 /DISK3/www/4172/petkapraha.cz/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /DISK3/www/4172/petkapraha.cz/www/wp-admin/admin-ajax.php(188): do_action()
#12 {main}

po 2 hodinách autorizace zmizí
![image (1)](https://github.com/skaut/skaut-google-drive-gallery/assets/8988898/b2fe3dcd-ba57-4c44-b8b9-189bb6c739ad)

![image](https://github.com/skaut/skaut-google-drive-gallery/assets/8988898/40710ca4-1e65-4b8a-b877-95a9bc0df0ae)

**Comment by kalich5** [comment]
https://stackoverflow.com/questions/39314833/google-api-client-refresh-token-must-be-passed-in-or-set-as-part-of-setaccessto

**Comment by kalich5** [comment]
Solved by creating a new Google app and linking to the website
