### ISSUE TITLE
Error with Google API batching

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-google-drive-gallery#2622]
Since the last release, some update broke batching in the Google API.

```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Sgdg\Vendor\Google\Http\Batch::add(): Argument #1 ($request) must be of type Sgdg\Vendor\Psr\Http\Message\RequestInterface, Sgdg\Vendor\Google\Service\Drive\Drive given, called in /home/user/site/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php on line 162 and defined in /home/user/site/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Http/Batch.php:53
Stack trace:
#0 /home/user/site/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(162): Sgdg\Vendor\Google\Http\Batch-&gt;add()
#1 /home/user/site/wp-content/plugins/skaut-google-drive-gallery/class-api-facade.php(103): Sgdg\API_Client::async_request()
#2 /home/user/site/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(132): Sgdg\API_Facade::get_drive_name()
#3 /home/user/site/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(75): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::path_ids_to_names()
#4 /home/user/site/wp-content/plugins/skaut-google-drive-gallery/helpers/class-helpers.php(42): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::ajax_handler_body()
#5 /home/user/site/wp-content/plugins/skaut-google-drive-gallery/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php(53): Sgdg\Helpers::ajax_wrapper()
#6 /home/user/site/wp-includes/class-wp-hook.php(324): Sgdg\Admin\Settings_Pages\Basic\Root_Selection\List_Ajax_Endpoint::handle_ajax()
#7 /home/user/site/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#8 /home/user/site/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#9 /home/user/site/wp-admin/admin-ajax.php(192): do_action()
#10 {main}
  thrown in <b>/home/user/site/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/Http/Batch.php</b> on line <b>53</b><br />
<p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/documentation/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p>
```

**Comment by marekdedic** [comment]
Looks like the issue was introduced in fa1b2ddf4f310c52ad68044c0c8f72de97ed84c4
