### ISSUE TITLE
Too many photos causes app to crash

### ISSUE THREAD

**Issue by rhogro** [skaut/skaut-google-drive-gallery#2679]
I have a big folder with more than 1700 photos. After scrolling and loading a bunch of them (1000), I get the following error (sorry for not being too detailed):
`The Image and video gallery from Google Drive plugin has encountered an error. Error message:

An internal error happened in the gallery.

Stack trace:

#0 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(239): Sgdg\API_Client::Sgdg\{closure}('~!!~AI9FV7Qlai0...', Object(Sgdg\Vendor\GuzzleHttp\Promise\Promise), Array)
#1 [internal function]: Sgdg\API_Client::Sgdg\{closure}(Object(Sgdg\Vendor\Google\Service\Drive\FileList))
#2 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(331): call_user_func(Object(Closure), Object(Sgdg\Vendor\Google\Service\Drive\FileList))
#3 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(260): Sgdg\API_Client::execute_current_batch()
#4 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/class-api-client.php(264): Sgdg\API_Client::execute()
#5 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/frontend/class-page.php(65): Sgdg\API_Client::execute(Array)
#6 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/helpers/class-helpers.php(42): Sgdg\Frontend\Page::ajax_handler_body()
#7 /home3/urmepplayr/public_html/wp-content/plugins/skaut-google-drive-gallery/frontend/class-page.php(46): Sgdg\Helpers::ajax_wrapper(Array)
#8 /home3/urmepplayr/public_html/wp-includes/class-wp-hook.php(324): Sgdg\Frontend\Page::handle_ajax('')
#9 /home3/urmepplayr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /home3/urmepplayr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /home3/urmepplayr/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_page')
#12 {main}`

**Comment by marekdedic** [comment]
Hi,
thanks for the report, I have a few questions which should help me to better pinpoint the issue:
1. Do I understand it correctly that the issue happens after loading a lot of, but **not all** images in the folder?
2. Do you have automatic loading of new pages enabled?
3. What is your configured page size?
4. Could you please try to change the page size (incerease it) and see if it has any effect?
5. Could you please try disabling auto-loading of next page and see if it has any effect?

Thanks!
